//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web404.CMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostSummary
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public bool Active { get; set; }
        public string SID { get; set; }
        public string Partition { get; set; }
        public string Title { get; set; }
        public string Summary { get; set; }
        public string Body { get; set; }
        public int PostTypeID { get; set; }
        public string TagList { get; set; }
    }
}
