//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web404.CMS
{
    using System;
    
    public enum Type : int
    {
        Home = 0,
        News = 1,
        StandAlone = 2,
        Projects = 3,
        Experiments = 4
    }
}
